"""
Code Dojo Recap Engine — post-challenge learning for agents.

After every challenge, the recap engine analyzes all submissions and generates
structured learning data that feeds into the agent's persistent memory. This is
what makes Code Dojo a training ground, not just a bounty platform.

Recaps are:
  1. Generated by an LLM (analyzing all submissions + the challenge context)
  2. Stored per-contributor in the ledger
  3. Loaded as context before the agent's next challenge
  4. Accumulate over time — the agent gets smarter with every challenge

Future: agents trained through many challenges become sellable assets (marketplace).
"""

import json
import os
import sqlite3
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Optional

import requests

# LLM config — uses OpenRouter by default (Buck already has a key)
OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY", "")
OPENROUTER_BASE = "https://openrouter.ai/api/v1/chat/completions"
RECAP_MODEL = os.environ.get("RECAP_MODEL", "anthropic/claude-sonnet-4.6")

DB_PATH = Path(__file__).parent / "dojo.db"

RECAP_SYSTEM_PROMPT = """You are the Dojo Recap Engine. Your job is to analyze coding battle results and generate structured learning recaps for AI agents.

You receive:
- The battle task (GitHub issue description)
- The winning submission (code diff)
- The losing submission (code diff)
- The battle outcome (score, win/loss)

You produce a structured recap in JSON with these fields:
{
  "winner_analysis": "What the winning approach did right — specific techniques, patterns, strategies",
  "loser_analysis": "What the losing approach missed — specific gaps, mistakes, suboptimal choices",
  "key_techniques": ["List of specific techniques that worked well"],
  "patterns_to_avoid": ["List of anti-patterns or mistakes observed"],
  "improvement_suggestions": ["Specific actionable advice for the loser's next battle"],
  "difficulty_assessment": "Was this battle harder/easier than expected? Why?",
  "skill_tags": ["What skills were tested: e.g. 'error-handling', 'async', 'parsing', 'testing'"]
}

Be specific and technical. This recap will be fed into an AI agent's memory to improve its next performance. Vague advice is useless; concrete patterns are gold."""


@dataclass
class BattleRecap:
    """A structured recap generated after a battle."""
    battle_id: int
    winner_id: int
    loser_id: int
    winner_analysis: str
    loser_analysis: str
    key_techniques: list[str]
    patterns_to_avoid: list[str]
    improvement_suggestions: list[str]
    difficulty_assessment: str
    skill_tags: list[str]
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())

    def for_winner(self) -> str:
        """Format the recap for the winner's agent memory."""
        return (
            f"BATTLE WON — Skills tested: {', '.join(self.skill_tags)}\n"
            f"What worked: {self.winner_analysis}\n"
            f"Techniques to repeat: {', '.join(self.key_techniques)}\n"
            f"Difficulty: {self.difficulty_assessment}\n"
        )

    def for_loser(self) -> str:
        """Format the recap for the loser's agent memory."""
        return (
            f"BATTLE LOST — Skills tested: {', '.join(self.skill_tags)}\n"
            f"What the opponent did better: {self.winner_analysis}\n"
            f"Where you fell short: {self.loser_analysis}\n"
            f"Next time try: {'; '.join(self.improvement_suggestions)}\n"
            f"Avoid: {'; '.join(self.patterns_to_avoid)}\n"
            f"Difficulty: {self.difficulty_assessment}\n"
        )

    def to_json(self) -> str:
        return json.dumps({
            "battle_id": self.battle_id,
            "winner_id": self.winner_id,
            "loser_id": self.loser_id,
            "winner_analysis": self.winner_analysis,
            "loser_analysis": self.loser_analysis,
            "key_techniques": self.key_techniques,
            "patterns_to_avoid": self.patterns_to_avoid,
            "improvement_suggestions": self.improvement_suggestions,
            "difficulty_assessment": self.difficulty_assessment,
            "skill_tags": self.skill_tags,
            "created_at": self.created_at,
        }, indent=2)


def init_recaps_table():
    """Add recaps table to the Dojo database."""
    db = sqlite3.connect(str(DB_PATH))
    db.executescript("""
    CREATE TABLE IF NOT EXISTS battle_recaps (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        battle_id INTEGER,
        contributor_id INTEGER,
        recap_json TEXT NOT NULL,
        formatted_recap TEXT NOT NULL,
        created_at TEXT NOT NULL
    );
    """)
    db.commit()
    db.close()


def generate_recap(
    battle_id: int,
    battle_title: str,
    battle_body: str,
    winner_id: int,
    loser_id: int,
    winner_code: str,
    loser_code: str,
    winner_score: float,
    loser_score: float,
) -> Optional[BattleRecap]:
    """Generate a battle recap using an LLM.

    If no API key is available, returns a basic heuristic recap.
    """
    if not OPENROUTER_API_KEY:
        return _heuristic_recap(
            battle_id, winner_id, loser_id,
            winner_code, loser_code, winner_score, loser_score
        )

    user_prompt = f"""Analyze this coding battle:

BATTLE TASK:
Title: {battle_title}
Description: {battle_body[:1000]}

WINNER (score: {winner_score:.0f}):
```{winner_code[:3000]}```

LOSER (score: {loser_score:.0f}):
```{loser_code[:3000]}```

Generate the structured recap as JSON."""

    try:
        resp = requests.post(
            OPENROUTER_BASE,
            headers={
                "Authorization": f"Bearer {OPENROUTER_API_KEY}",
                "Content-Type": "application/json",
            },
            json={
                "model": RECAP_MODEL,
                "messages": [
                    {"role": "system", "content": RECAP_SYSTEM_PROMPT},
                    {"role": "user", "content": user_prompt},
                ],
                "response_format": {"type": "json_object"},
                "temperature": 0.3,
            },
            timeout=30,
        )
        resp.raise_for_status()
        data = resp.json()["choices"][0]["message"]["content"]
        parsed = json.loads(data)

        return BattleRecap(
            battle_id=battle_id,
            winner_id=winner_id,
            loser_id=loser_id,
            winner_analysis=parsed.get("winner_analysis", ""),
            loser_analysis=parsed.get("loser_analysis", ""),
            key_techniques=parsed.get("key_techniques", []),
            patterns_to_avoid=parsed.get("patterns_to_avoid", []),
            improvement_suggestions=parsed.get("improvement_suggestions", []),
            difficulty_assessment=parsed.get("difficulty_assessment", ""),
            skill_tags=parsed.get("skill_tags", []),
        )
    except Exception as e:
        # Fall back to heuristic if LLM fails
        return _heuristic_recap(
            battle_id, winner_id, loser_id,
            winner_code, loser_code, winner_score, loser_score
        )


def _heuristic_recap(
    battle_id: int, winner_id: int, loser_id: int,
    winner_code: str, loser_code: str,
    winner_score: float, loser_score: float,
) -> BattleRecap:
    """Basic recap without LLM — used when no API key or LLM fails."""
    winner_has_structure = any(kw in winner_code for kw in ["def ", "class ", "function ", "impl "])
    loser_has_structure = any(kw in loser_code for kw in ["def ", "class ", "function ", "impl "])

    techniques = []
    if winner_has_structure:
        techniques.append("Used proper code structure (functions/classes)")
    if len(winner_code) > len(loser_code):
        techniques.append("More complete solution")
    if any(kw in winner_code for kw in ["if ", "else", "try", "except"]):
        techniques.append("Included error handling / edge cases")

    avoid = []
    if not loser_has_structure:
        avoid.append("No structured code definitions")
    if "TODO" in loser_code or "FIXME" in loser_code:
        avoid.append("Left TODO/FIXME markers")
    if "print(" in loser_code or "console.log" in loser_code:
        avoid.append("Debug statements left in code")

    return BattleRecap(
        battle_id=battle_id,
        winner_id=winner_id,
        loser_id=loser_id,
        winner_analysis=f"Winner scored {winner_score:.0f} with a {'structured' if winner_has_structure else 'simple'} solution.",
        loser_analysis=f"Loser scored {loser_score:.0f}. {'Lacked proper code structure.' if not loser_has_structure else 'Solution was less complete.'}",
        key_techniques=techniques,
        patterns_to_avoid=avoid,
        improvement_suggestions=[
            "Add proper function/class structure",
            "Handle edge cases",
            "Remove debug artifacts before submitting",
        ],
        difficulty_assessment=f"Score gap: {winner_score - loser_score:.0f} points",
        skill_tags=["general"],
    )


def store_recap(recap: BattleRecap):
    """Store a recap for both the winner and loser in the database."""
    db = sqlite3.connect(str(DB_PATH))
    db.execute("PRAGMA foreign_keys = ON")

    # Store for winner (positive learning) — skip if no winner (solo loss)
    if recap.winner_id and recap.winner_id > 0:
        db.execute(
            """INSERT INTO battle_recaps (battle_id, contributor_id, recap_json, formatted_recap, created_at)
               VALUES (?, ?, ?, ?, ?)""",
            (recap.battle_id, recap.winner_id, recap.to_json(), recap.for_winner(), recap.created_at)
        )

    # Store for loser (corrective learning) — skip if no loser (solo win)
    if recap.loser_id and recap.loser_id > 0:
        db.execute(
            """INSERT INTO battle_recaps (battle_id, contributor_id, recap_json, formatted_recap, created_at)
               VALUES (?, ?, ?, ?, ?)""",
            (recap.battle_id, recap.loser_id, recap.to_json(), recap.for_loser(), recap.created_at)
        )

    db.commit()
    db.close()


def get_agent_memory(contributor_id: int, limit: int = 20) -> str:
    """Load a contributor's battle recaps as context for their agent.

    This is the persistent memory that makes agents get smarter over time.
    Called before each battle and injected into the agent's context.
    """
    db = sqlite3.connect(str(DB_PATH))
    db.row_factory = sqlite3.Row
    rows = db.execute(
        """SELECT formatted_recap, created_at FROM battle_recaps
           WHERE contributor_id = ?
           ORDER BY created_at DESC LIMIT ?""",
        (contributor_id, limit)
    ).fetchall()
    db.close()

    if not rows:
        return ""

    lines = ["=== BATTLE MEMORY (past recaps) ==="]
    for row in rows:
        lines.append(row["formatted_recap"])
        lines.append("---")
    return "\n".join(lines)


def get_recap_history(contributor_id: int, limit: int = 10) -> list[dict]:
    """Get recap history for display (e.g. in Telegram /status)."""
    db = sqlite3.connect(str(DB_PATH))
    db.row_factory = sqlite3.Row
    rows = db.execute(
        """SELECT battle_id, recap_json, created_at FROM battle_recaps
           WHERE contributor_id = ?
           ORDER BY created_at DESC LIMIT ?""",
        (contributor_id, limit)
    ).fetchall()
    db.close()
    return [dict(r) for r in rows]


if __name__ == "__main__":
    init_recaps_table()
    print("Recap engine initialized. Database:", DB_PATH)
